--- 
title: "Offshore Scallop Survey Summary"
subtitle: "Summer 2026"
author: "Scallop and Benthic Habitat Unit"
output: 
  bookdown::pdf_document2:
    extra_dependencies: ["float"]
    toc: yes
    toc_depth: 1
header-includes:
 - \usepackage{float}
 - \usepackage{fancyhdr}
 - \pagestyle{fancy}
 - \fancyfoot[CO,CE]{Summer Survey 2026}
 - \fancyfoot[LE,RO]{\thepage}
---

```{r, echo=F, message=F, warning=F}
require(lubridate)
load("summary2.Rdata")

dates <- summary_data$dates[summary_data$dates$bank %in% c(#"Mid", "Sab", "Ger", "BBn", "BBs", "GB",
                                                           "GBa", "GBb"
                                                           ),]
# for dates:
# `r stamp("March 1")(min(dates$start)-days(1))` to `r stamp("March 1, 2021")(max(dates$end) + days(1))`
```

 
\newpage


# Survey overview

The Summer Offshore Scallop Survey occurred from July 31 to August 11, 2026 on Georges Bank 'a' and 'b'. The Chief Scientist was Tricia Pearo Drew, and the survey was carried out on the Fundy Leader.

This report summarizes the information collected during the survey. At each survey station, the 8-ft scallop dredge is towed for 10 minutes, and all sea scallops are counted and assigned to 5mm shell height bins (ranging from 0-200mm). This information informs the abundance time series, shell height frequency, clapper time series, and spatial distribution figures. 

Detailed sampling occurred at a selection of the stations, where the exact shell heights and meat weights are recorded for a subsample of the scallops caught. This allows for the calculation of biomass and condition that are presented in the biomass time series, meat weight-shell height relationship, and condition time series figures. 

Some of the figures and analyses presented in this report refer to the different size classes of scallop: pre-recruits, recruits, and fully-recruited scallops. The shell height range for each size class differs by bank, but the general convention is that recruits are expected to grow to commercial size in the next year, while fully-recruited scallops were commercial size at the time of the survey. 

We also compare values from the current survey to the most recent previous survey, and/or to long term medians. In this report, all long term medians exclude the value from the current year. 

Note that the DFO stock assessment framework uses survey data related to the biomass, growth and mortality of recruit and fully-recruited scallop. Data on pre-recruits are not included in the stock assessment framework, but figures are provided here as they may offer additional context for long-term harvest planning.